# Dockerfile for building and serving a Vite static site
FROM node

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build 

RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]


# Alternative Dockerfile for development

# Client/Dockerfile
# FROM node

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# EXPOSE 5173

# CMD ["npm", "run", "dev"]
