version: '3.8'

services:
  client:
    build:
      context: ./Client
    image: jsonbrewer/smartlint-client
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build:
      context: ./Server
    image: jsonbrewer/smartlint-server
    ports:
      - "7600:7600"
    env_file:
      - ./Server/.env
